#!/usr/bin/env python

"""
Problem Definition :

    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

# First two Fibonacci set to 1,1.
a = 1
b = 1

total = 0

#While the Fibonnaci is less than the given limit - 4 million, find next Fibonnaci and add to total if it is even.

while b < 4000000 :
    a,b = b,a+b
    
    if b%2 == 0 :
        total = total + b

print total
