#!/usr/bin/env python
# coding=utf-8

# IN PROGRESS #
"""
Problem Definition :

Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers Pj and Pk for which their sum and difference are pentagonal and D = Pk − Pj is minimised what is the value of D?

"""

__author__ = 'vivek'

import time
import math

startTime = time.clock()


def pentagonal(n):
    return n*(3*n - 1)/2


penta_numbers = [pentagonal(x) for x in xrange(1,10000)]
print(62710501 in penta_numbers)

print "Run time...{} secs \n".format(round(time.clock() - startTime, 4))
answers = []
print(len(penta_numbers))

for i in xrange(0,9999):
    for j in xrange(i+1,9999) :
        number1 = penta_numbers[i]
        number2 = penta_numbers[j]
        if number2-number1 in penta_numbers :#and abs(number2-number1) in penta_numbers:
            answers.append(abs(number2-number1))
            #print("Found")
            print(number1, number2)
if answers:
    print(min(answers))
else:
    print("Not found")

print(penta_numbers)

print "Run time...{} secs \n".format(round(time.clock() - startTime, 4))
